In [541]:
import pandas as pd
import seaborn as sns

In [685]:
testdf = pd.read_csv('test.csv')


In [651]:
traindf = pd.read_csv('train.csv')

In [652]:
testdf.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [653]:
traindf.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [654]:
print(testdf.shape)
print(traindf.shape)

(418, 11)
(891, 12)


In [655]:
traindf.isnull().sum()/len(traindf)*100

PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            19.865320
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
Embarked        0.224467
dtype: float64

In [656]:
testdf.isnull().sum()/len(testdf)*100

PassengerId     0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            20.574163
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.239234
Cabin          78.229665
Embarked        0.000000
dtype: float64

In [657]:
testdf.drop(['Cabin','Name','Ticket','Fare','SibSp'], axis = 1 ,inplace = True)
traindf.drop(['Cabin','Name','Ticket','Fare','SibSp'], axis =1 , inplace = True)

In [658]:
testdf.head(1)

PassengerId  Pclass   Sex   Age  Parch Embarked
0          892       3  male  34.5      0        Q

In [659]:
traindf.head(1)

PassengerId  Survived  Pclass   Sex   Age  Parch Embarked
0            1         0       3  male  22.0      0        S

In [660]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

In [661]:
traindf['sex'] = le.fit_transform(traindf.Sex)
testdf['sex']  = le.fit_transform(testdf.Sex)

traindf.drop(['Sex'], axis =1, inplace = True)
testdf.drop(['Sex'], axis =1, inplace = True)

In [662]:
traindf['embarked']= le.fit_transform(traindf['Embarked'])
testdf['embarked'] = le.fit_transform(testdf.Embarked)

traindf.drop(['Embarked'],axis=1,inplace = True)
testdf.drop(['Embarked'],axis=1, inplace = True)

In [663]:
print(traindf.shape)
print(testdf.shape)

(891, 7)
(418, 6)


In [664]:
traindf.Age.describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [665]:
testdf.Age.describe()

count    332.000000
mean      30.272590
std       14.181209
min        0.170000
25%       21.000000
50%       27.000000
75%       39.000000
max       76.000000
Name: Age, dtype: float64

In [666]:
#import numpy as np
#bins = np.linspace(min(df.Age),max(df.Age), 9)
#group_name = ['0-10','11-20','21-30','31-40','41-50','51-60','61-70','71-80']

#traindf['Age_bin'] = pd.cut(traindf['Age'], bins = bins , labels = group_name , include_lowest=True)

#testdf['Age_bin'] = pd.cut(testdf['Age'], bins = bins , labels = group_name , include_lowest=True)

In [667]:
traindf.head(10)

PassengerId  Survived  Pclass   Age  Parch  sex  embarked
0            1         0       3  22.0      0    1         2
1            2         1       1  38.0      0    0         0
2            3         1       3  26.0      0    0         2
3            4         1       1  35.0      0    0         2
4            5         0       3  35.0      0    1         2
5            6         0       3   NaN      0    1         1
6            7         0       1  54.0      0    1         2
7            8         0       3   2.0      1    1         2
8            9         1       3  27.0      2    0         2
9           10         1       2  14.0      0    0         0

In [668]:
traindf.groupby(['sex'])['Age'].mean()

sex
0    27.915709
1    30.726645
Name: Age, dtype: float64

In [669]:
testdf.groupby(['sex'])['Age'].mean()

sex
0    30.272362
1    30.272732
Name: Age, dtype: float64

In [670]:
traindf.loc[(traindf.Age.isnull()) & (traindf.sex == False),'Age'] = 27.91

In [671]:
traindf.loc[(traindf.Age.isnull()) & (traindf.sex == True), 'Age'] = 30.72

In [672]:
traindf.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Age            0
Parch          0
sex            0
embarked       0
dtype: int64

In [673]:
testdf.isnull().sum()

PassengerId     0
Pclass          0
Age            86
Parch           0
sex             0
embarked        0
dtype: int64

In [674]:
testdf.loc[(testdf.Age.isnull()) & (testdf.sex == True),'Age'] = 30.72
testdf.loc[(testdf.Age.isnull())& (testdf.sex== False),'Age'] = 30.72

In [675]:
from sklearn.model_selection import train_test_split
#from sklearn.model_selection import train_test_split

In [676]:
x_train,x_test,y_trian,y_test=train_test_split(traindf[['embarked','Pclass','Age','Parch','sex']],traindf.Survived,test_size = 0.30)

In [678]:
traindf.drop(['PassengerId'],axis =1,inplace = True)

In [679]:
traindf.head(1)

Survived  Pclass   Age  Parch  sex  embarked
0         0       3  22.0      0    1         2

In [614]:
from sklearn import 

SyntaxError: invalid syntax (3750712168.py, line 1)

In [680]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
#class3 = KNeighborsClassifier(n_neighbors=5)
#class3.fit(x_train, y_trian)
#b = class3.predict(testdf)
#model = LogisticRegression()
#model.fit(x_train,y_trian)
#model.predict(x_test)
#model.score(x_test,y_test)

In [681]:
log = LogisticRegression()
knn = KNeighborsClassifier()

In [682]:
print(log)
print(knn)

LogisticRegression()
KNeighborsClassifier()


In [683]:
log.fit(x_train,y_trian)

LogisticRegression()

In [684]:
log.predict(x_test)
log.score(x_test,y_test)
a = log.predict(testdf)

C:\Users\Ajeet\anaconda3\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names must be in the same order as they were in fit.

  warnings.warn(message, FutureWarning)


In [621]:
knn.fit(x_train,y_trian)
knn.predict(x_test)
knn.score(x_test,y_test)

0.7686567164179104

In [626]:
a = knn.predict(testdf)

C:\Users\Ajeet\anaconda3\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names must be in the same order as they were in fit.

  warnings.warn(message, FutureWarning)


In [686]:
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [634]:
b = testdf.PassengerId

In [687]:
b = pd.DataFrame({'Survived':a})
c = pd.DataFrame(testdf['PassengerId'])

In [688]:
d=c.join(b)

In [689]:
d.to_csv('knpredict.csv',index= False)

#final_knn_.to_csv('finalsumitknn.csv',index=False)

In [690]:
d

PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         0
..           ...       ...
413         1305         0
414         1306         0
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

LogisticRegression()

In [411]:
model.score(x_test,y_test)

0.8333333333333334

C:\Users\Ajeet\anaconda3\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names must be in the same order as they were in fit.

  warnings.warn(message, FutureWarning)


array([1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0,

418

418

Survived
0           1
1           0
2           1
3           0
4           0
..        ...
413         0
414         1
415         0
416         0
417         0

[418 rows x 1 columns]

In [482]:
final_knn_      # PassengerId

PassengerId  Survived
0            892         1
1            893         0
2            894         1
3            895         0
4            896         0
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [428]:
final

PassengerId  Survived
0            892         1
1            893         0
2            894         0
3            895         1
4            896         1
..           ...       ...
413         1305         1
414         1306         0
415         1307         1
416         1308         1
417         1309         1

[418 rows x 2 columns]

In [ ]:
x_train,x_test,y_trian,y_test

In [467]:
from sklearn.neighbors import KNeighborsClassifier
class3 = KNeighborsClassifier(n_neighbors=5)
class3.fit(x_train, y_trian)
b = class3.predict(testdf)


C:\Users\Ajeet\anaconda3\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- Age
Feature names seen at fit time, yet now missing:
- SibSp

  warnings.warn(message, FutureWarning)


In [468]:
len(b)

418

In [469]:
b

array([1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,

model = LogisticRegression()